[package]
name = "npm-rs"
version = "0.1.0"
authors = ["Jeff Dickey"]

[dependencies]
digest = { version = "0.7", features = ["std"] }
reqwest = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha-1 = "0.7"
tar = "0.4"
xx = { path = "../xx" }
flate2 = "1.0.2"
rayon = "1.0.2"
